# -*- coding: utf-8 -*-
"""Copia de ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NGPQLNZmBhNBDD0p70Vli52OIZ8iK9-
"""

# ============================================
# DETECCIÓN DE NEUMONÍA CON RED NEURONAL CNN
# ============================================

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print("TensorFlow:", tf.__version__)
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# ============================================
# CONFIGURACIÓN DEL PROYECTO
# ============================================

import os

# Crear las carpetas del proyecto
os.makedirs("dataset/normal", exist_ok=True)
os.makedirs("dataset/neumonia", exist_ok=True)

print("Carpetas creadas correctamente.")
print(" - dataset/normal")
print(" - dataset/neumonia")

# ============================================
# DESCARGAR DATASET DE RADIOGRAFÍAS
# ============================================

!wget -q https://www.kaggle.com/api/v1/datasets/download/assemelqirsh/chest-x-ray-dataset -O dataset.zip

print("Descarga terminada.")

# ============================================
# DESCOMPRIMIR DATASET
# ============================================

import zipfile
import os

with zipfile.ZipFile("dataset.zip", "r") as zip_ref:
    zip_ref.extractall("datos")

print("Dataset descomprimido correctamente.")

# ============================================
# COMPROBAR LAS IMÁGENES
# ============================================

import os

for raiz, carpetas, archivos in os.walk("datos"):
    imagenes = [a for a in archivos if a.lower().endswith((".jpg", ".jpeg", ".png"))]

    if imagenes:
        print("Carpeta:", raiz)
        print("Cantidad de imágenes:", len(imagenes))

# ============================================
# PREPARAR UN SUBCONJUNTO PEQUEÑO
# ============================================

import tensorflow as tf

ruta_entrenamiento = "datos/chest_xray/train"

dataset = tf.keras.utils.image_dataset_from_directory(
    ruta_entrenamiento,
    labels="inferred",
    label_mode="binary",
    image_size=(128, 128),
    batch_size=8,
    shuffle=True,
    seed=42
)

print("Clases encontradas:", dataset.class_names)

# ============================================
# CREAR LA RED NEURONAL CONVOLUCIONAL
# ============================================

modelo = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255, input_shape=(128, 128, 3)),

    tf.keras.layers.Conv2D(16, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(32, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(1, activation="sigmoid")
])

modelo.summary()

# ============================================
# CREAR LA RED NEURONAL CONVOLUCIONAL
# ============================================

modelo = tf.keras.Sequential([
    tf.keras.Input(shape=(128, 128, 3)),

    tf.keras.layers.Rescaling(1./255),

    tf.keras.layers.Conv2D(16, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(32, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3, 3), activation="relu"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(1, activation="sigmoid")
])

modelo.summary()

# ============================================
# PREPARAR UN SUBCONJUNTO PEQUEÑO
# ============================================

dataset_pequeno = dataset.take(25)

print("Dataset pequeño preparado correctamente.")

# ============================================
# COMPILAR EL MODELO
# ============================================

modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("Modelo compilado correctamente.")

# ============================================
# ENTRENAMIENTO DE LA CNN
# ============================================

historial = modelo.fit(
    dataset_pequeno,
    epochs=3
)

# ============================================
# GRAFICAR EL ENTRENAMIENTO
# ============================================

plt.figure(figsize=(8, 5))

plt.plot(historial.history["accuracy"], marker="o")

plt.title("Precisión durante el entrenamiento")
plt.xlabel("Época")
plt.ylabel("Accuracy")
plt.ylim(0, 1)

plt.show()

# ============================================
# CARGAR DATOS DE PRUEBA
# ============================================

ruta_prueba = "datos/chest_xray/test"

dataset_prueba = tf.keras.utils.image_dataset_from_directory(
    ruta_prueba,
    labels="inferred",
    label_mode="binary",
    image_size=(128, 128),
    batch_size=8,
    shuffle=False
)

print("Clases:", dataset_prueba.class_names)

# ============================================
# EVALUAR EL MODELO
# ============================================

resultado = modelo.evaluate(dataset_prueba, verbose=1)

print("\nResultados de la evaluación:")
print("Loss:", round(resultado[0], 4))
print("Accuracy:", round(resultado[1] * 100, 2), "%")

# ============================================
# REALIZAR UNA PREDICCIÓN
# ============================================

for imagenes, etiquetas in dataset_prueba.take(1):

    predicciones = modelo.predict(imagenes)

    for i in range(3):

        probabilidad = float(predicciones[i][0])

        if probabilidad >= 0.5:
            prediccion = "PNEUMONIA"
        else:
            prediccion = "NORMAL"

        real = "PNEUMONIA" if int(etiquetas[i]) == 1 else "NORMAL"

        plt.figure(figsize=(4, 4))
        plt.imshow(imagenes[i].numpy().astype("uint8"))
        plt.axis("off")
        plt.title(
            f"Predicción: {prediccion}\n"
            f"Real: {real}\n"
            f"Probabilidad: {probabilidad:.2%}"
        )
        plt.show()

# ============================================
# PREDICCIÓN DE UNA RADIOGRAFÍA
# ============================================

for imagenes, etiquetas in dataset_prueba.take(1):

    imagen = imagenes[0]
    etiqueta_real = int(etiquetas[0])

    prediccion = modelo.predict(
        tf.expand_dims(imagen, axis=0),
        verbose=0
    )[0][0]

    if prediccion >= 0.5:
        clase_predicha = "PNEUMONIA"
    else:
        clase_predicha = "NORMAL"

    clase_real = "PNEUMONIA" if etiqueta_real == 1 else "NORMAL"

    plt.figure(figsize=(6, 6))
    plt.imshow(imagen.numpy().astype("uint8"))
    plt.axis("off")

    plt.title(
        f"Predicción: {clase_predicha}\n"
        f"Clase real: {clase_real}\n"
        f"Probabilidad: {prediccion:.2%}"
    )

    plt.show()

    print("Predicción del modelo:", clase_predicha)
    print("Clase real:", clase_real)