# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uBF9HLwM8sOEraVkDtyUs5L74LAA_4Y
"""

# ============================================
# PROYECTO: PREDICCIÓN DEL ABANDONO ESTUDIANTIL
# ============================================

# Importar las librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Librerías cargadas correctamente ✅")

# ============================================
# PASO 2: CARGAR EL DATASET
# ============================================

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00488/day.csv"

df = pd.read_csv(url)

print("Dataset cargado correctamente ✅")
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

# Mostrar las primeras filas
df.head()

# ============================================
# PASO 2: CARGAR DATASET DE ESTUDIANTES
# ============================================

!pip install -q ucimlrepo

from ucimlrepo import fetch_ucirepo

# Cargar el dataset de UCI
dataset = fetch_ucirepo(id=697)

# Separar características y variable objetivo
X = dataset.data.features
y = dataset.data.targets

print("Dataset cargado correctamente ✅")
print("Cantidad de estudiantes:", X.shape[0])
print("Cantidad de características:", X.shape[1])

print("\nPrimeras 5 filas:")
display(X.head())

print("\nVariable objetivo:")
display(y.head())

# ============================================
# PASO 3: EXPLORACIÓN DEL DATASET
# ============================================

print("Información general del dataset:")
print("----------------------------------")

print("Número de estudiantes:", X.shape[0])
print("Número de características:", X.shape[1])

print("\nTipos de datos:")
print("----------------------------------")
print(X.dtypes)

print("\nValores faltantes:")
print("----------------------------------")
print(X.isnull().sum().sum())

print("\nDistribución de la variable objetivo:")
print("----------------------------------")
print(y.value_counts())

# ============================================
# PASO 4: CREAR UNA MUESTRA DE 1000 ESTUDIANTES
# ============================================

# Combinar las características con la variable objetivo
data = X.copy()
data["Target"] = y["Target"].values

# Crear variable binaria:
# 1 = Abandono
# 0 = No abandono
data["Abandono"] = (data["Target"] == "Dropout").astype(int)

# Seleccionar 1000 estudiantes manteniendo
# la proporción entre las clases
data_sample = data.groupby("Abandono", group_keys=False).apply(
    lambda x: x.sample(
        n=int(1000 * len(x) / len(data)),
        random_state=42
    )
).reset_index(drop=True)

# Separar nuevamente características y objetivo
X = data_sample.drop(columns=["Target", "Abandono"])
y_binary = data_sample["Abandono"]

print("Muestra creada correctamente ✅")
print("----------------------------------")
print("Número de estudiantes:", len(data_sample))
print()

print("Distribución:")
print(y_binary.value_counts())

print("\nPorcentajes:")
print((y_binary.value_counts(normalize=True) * 100).round(2))

# ============================================
# PASO 5: DIVISIÓN DE LOS DATOS
# ============================================

# Primera división:
# 70% entrenamiento y 30% temporal
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y_binary,
    test_size=0.30,
    random_state=42,
    stratify=y_binary
)

# Segunda división:
# 15% validación y 15% prueba
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("División de los datos realizada correctamente ✅")
print("----------------------------------")

print("Entrenamiento:", len(X_train), "estudiantes")
print("Validación:", len(X_val), "estudiantes")
print("Prueba:", len(X_test), "estudiantes")

print("\nTotal:", len(X_train) + len(X_val) + len(X_test))

# ============================================
# PASO 6: ENTRENAMIENTO DEL MODELO
# ============================================

# Crear el modelo Random Forest
modelo = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

# Entrenar el modelo
modelo.fit(X_train, y_train)

print("Modelo Random Forest entrenado correctamente ✅")

# ============================================
# PASO 7: EVALUACIÓN CON EL CONJUNTO DE VALIDACIÓN
# ============================================

# Realizar predicciones
y_val_pred = modelo.predict(X_val)

# Calcular métricas
accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred)
recall = recall_score(y_val, y_val_pred)
f1 = f1_score(y_val, y_val_pred)

print("RESULTADOS DEL MODELO")
print("----------------------------------")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

# ============================================
# PASO 8: MATRIZ DE CONFUSIÓN
# ============================================

cm = confusion_matrix(y_val, y_val_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["No abandono", "Abandono"],
    yticklabels=["No abandono", "Abandono"]
)

plt.xlabel("Predicción del modelo")
plt.ylabel("Valor real")
plt.title("Matriz de confusión - Conjunto de validación")
plt.show()

# ============================================
# PASO 9: IMPORTANCIA DE LAS CARACTERÍSTICAS
# ============================================

# Obtener la importancia de cada característica
importancias = pd.DataFrame({
    "Característica": X_train.columns,
    "Importancia": modelo.feature_importances_
})

# Ordenar de mayor a menor
importancias = importancias.sort_values(
    by="Importancia",
    ascending=False
)

# Mostrar las 10 características más importantes
print("10 características más importantes:")
print("----------------------------------")
display(importancias.head(10))

# Crear gráfica
plt.figure(figsize=(10, 6))

plt.barh(
    importancias.head(10)["Característica"][::-1],
    importancias.head(10)["Importancia"][::-1]
)

plt.xlabel("Importancia")
plt.ylabel("Característica")
plt.title("Principales características utilizadas por el modelo")
plt.tight_layout()
plt.show()

# ============================================
# PASO 10: AJUSTE DE HIPERPARÁMETROS
# ============================================

from sklearn.model_selection import GridSearchCV

# Parámetros que vamos a probar
parametros = {
    "n_estimators": [100, 200],
    "max_depth": [5, 10, 15],
    "min_samples_split": [2, 5],
    "class_weight": ["balanced"]
}

# Crear el modelo base
rf_base = RandomForestClassifier(random_state=42)

# Búsqueda de la mejor combinación
grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=parametros,
    scoring="f1",
    cv=5,
    n_jobs=-1
)

# Entrenar las diferentes configuraciones
grid_search.fit(X_train, y_train)

# Mostrar los mejores parámetros
print("Mejores parámetros encontrados:")
print("----------------------------------")
print(grid_search.best_params_)

print("\nMejor F1-Score durante la validación cruzada:")
print("----------------------------------")
print(round(grid_search.best_score_, 4))

# ============================================
# PASO 11: MODELO FINAL Y EVALUACIÓN
# ============================================

# Obtener el mejor modelo encontrado
modelo_final = grid_search.best_estimator_

# Evaluar primero con el conjunto de validación
y_val_pred_final = modelo_final.predict(X_val)
y_val_prob_final = modelo_final.predict_proba(X_val)[:, 1]

# Calcular métricas de validación
accuracy_val = accuracy_score(y_val, y_val_pred_final)
precision_val = precision_score(y_val, y_val_pred_final)
recall_val = recall_score(y_val, y_val_pred_final)
f1_val = f1_score(y_val, y_val_pred_final)
roc_auc_val = roc_auc_score(y_val, y_val_prob_final)

print("RESULTADOS DEL MODELO AJUSTADO - VALIDACIÓN")
print("------------------------------------------------")
print(f"Accuracy:  {accuracy_val:.4f}")
print(f"Precision: {precision_val:.4f}")
print(f"Recall:    {recall_val:.4f}")
print(f"F1-Score:  {f1_val:.4f}")
print(f"ROC-AUC:   {roc_auc_val:.4f}")


# ============================================
# EVALUACIÓN FINAL CON DATOS DE PRUEBA
# ============================================

y_test_pred = modelo_final.predict(X_test)
y_test_prob = modelo_final.predict_proba(X_test)[:, 1]

accuracy_test = accuracy_score(y_test, y_test_pred)
precision_test = precision_score(y_test, y_test_pred)
recall_test = recall_score(y_test, y_test_pred)
f1_test = f1_score(y_test, y_test_pred)
roc_auc_test = roc_auc_score(y_test, y_test_prob)

print("\nRESULTADOS FINALES - CONJUNTO DE PRUEBA")
print("------------------------------------------------")
print(f"Accuracy:  {accuracy_test:.4f}")
print(f"Precision: {precision_test:.4f}")
print(f"Recall:    {recall_test:.4f}")
print(f"F1-Score:  {f1_test:.4f}")
print(f"ROC-AUC:   {roc_auc_test:.4f}")

# ============================================
# PASO 12: MATRIZ DE CONFUSIÓN FINAL
# ============================================

cm_final = confusion_matrix(y_test, y_test_pred)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_final,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["No abandono", "Abandono"],
    yticklabels=["No abandono", "Abandono"]
)

plt.xlabel("Predicción del modelo")
plt.ylabel("Valor real")
plt.title("Matriz de confusión - Modelo final")
plt.tight_layout()
plt.show()

print("Matriz de confusión:")
print(cm_final)

# ============================================
# PASO 13: CURVA ROC
# ============================================

from sklearn.metrics import roc_curve, auc

# Calcular la curva ROC
fpr, tpr, thresholds = roc_curve(y_test, y_test_prob)

# Calcular AUC
roc_auc = auc(fpr, tpr)

# Crear la gráfica
plt.figure(figsize=(8, 6))

plt.plot(
    fpr,
    tpr,
    label=f"Random Forest (AUC = {roc_auc:.4f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Clasificación aleatoria"
)

plt.xlabel("Tasa de falsos positivos")
plt.ylabel("Tasa de verdaderos positivos")
plt.title("Curva ROC - Modelo final")
plt.legend()
plt.grid(True)
plt.show()

print(f"ROC-AUC del modelo final: {roc_auc:.4f}")

# ============================================
# PASO 14: ANÁLISIS DE EQUIDAD POR GÉNERO
# ============================================

# Crear una copia de los datos de prueba
equidad = X_test.copy()

# Agregar valores reales y predicciones
equidad["Real"] = y_test.values
equidad["Prediccion"] = y_test_pred

# Agregar el género
equidad["Genero"] = X_test["Gender"].values

print("Rendimiento del modelo según género")
print("--------------------------------------------")

for genero in sorted(equidad["Genero"].unique()):

    grupo = equidad[equidad["Genero"] == genero]

    recall_grupo = recall_score(
        grupo["Real"],
        grupo["Prediccion"],
        zero_division=0
    )

    precision_grupo = precision_score(
        grupo["Real"],
        grupo["Prediccion"],
        zero_division=0
    )

    print(f"\nGénero {genero}")
    print(f"Cantidad de estudiantes: {len(grupo)}")
    print(f"Recall: {recall_grupo:.4f}")
    print(f"Precision: {precision_grupo:.4f}")

# ============================================
# PASO 15: ANÁLISIS DE EQUIDAD POR EDAD
# ============================================

# Crear una copia de los datos de prueba
equidad_edad = X_test.copy()

# Agregar valores reales y predicciones
equidad_edad["Real"] = y_test.values
equidad_edad["Prediccion"] = y_test_pred

# Crear grupos de edad
equidad_edad["Grupo_edad"] = np.where(
    equidad_edad["Age at enrollment"] <= 25,
    "18-25 años",
    "26 años o más"
)

print("Rendimiento del modelo según grupo de edad")
print("--------------------------------------------")

for grupo_edad in equidad_edad["Grupo_edad"].unique():

    grupo = equidad_edad[
        equidad_edad["Grupo_edad"] == grupo_edad
    ]

    recall_grupo = recall_score(
        grupo["Real"],
        grupo["Prediccion"],
        zero_division=0
    )

    precision_grupo = precision_score(
        grupo["Real"],
        grupo["Prediccion"],
        zero_division=0
    )

    print(f"\nGrupo: {grupo_edad}")
    print(f"Cantidad de estudiantes: {len(grupo)}")
    print(f"Recall: {recall_grupo:.4f}")
    print(f"Precision: {precision_grupo:.4f}")